### ISSUE TITLE
U-Net Fusion

### ISSUE THREAD

**Issue by rpartsey** [FrontierDevelopmentLab/multi3net#1]
@timrudner  @MarcCoru Hi,

In the repository's _readme.md_ you stated that "This repository contains source code and data used in "_Segmenting Flooded Buildings via Fusion of Multiresolution, Multisensor, and Multitemporal Satellite Imagery_".

But the source code is configured to use PSPNet for image fusion.
Do you have U-Net data fusion architecture implementation, reported in your paper "_Segmenting Flooded Buildings via Fusion of Multiresolution, Multisensor, and Multitemporal Satellite Imagery_"?'

Thanks in advance,
Ruslan.

**Comment by MarcCoru** [comment]
Hi @rpartsey,

Thanks for your issue. 

The unet model can be found here
https://github.com/FrontierDevelopmentLab/multi3net/blob/master/src/models/unet_model.py
and 
https://github.com/FrontierDevelopmentLab/multi3net/blob/master/src/models/unet_parts.py
the source code originates from https://github.com/milesial/Pytorch-UNet/tree/master/unet

The training and prediction scripts in this repo include the PSPNet ablation experiments only.
To reproduce the unet experiments, you would need to add the Unet model in the if-else section here https://github.com/FrontierDevelopmentLab/multi3net/blob/e4dad0ed5165da34a9aa4fb0f597c044d2a2d8bb/src/train.py#L59

cheers,
marc

**Comment by rpartsey** [comment]
Resolved. Closing the issue.
